#!/usr/bin/env bash

# shellcheck disable=SC2129
# shellcheck disable=SC2034

# Function: process_actions
#
# Process action switch

process_actions () {
  if [ "${iso['action']}" = "" ]; then
    warning_message "No action specified"
    exit
  fi
  case "${iso['action']}" in
    help|printhelp)
      print_help
      ;;
    usage|printusage)
      print_usage
      ;;
    checkracadm)
      options['checkracadm']="true"
      ;;
    runracadm|execracadm|exectureracadm)
      options['checkracadm']="true"
      options['executeracadm']="true"
      ;;
    listvm)
      options['listvms']="true"
      ;;
    createexport)
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['createexport']="true"
      ;;
    createansible)
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['createansible']="true"
      ;;
    runansible)
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['createexport']="true"
      options['createansible']="true"
      options['installserver']="true"
      ;;
    printenv)
      options['printenv']="true"
      ;;
    checkdocker)
      options['docker']="false"
      options['checkdocker']="true"
      options['checkworkdir']="true"
      ;;
    getiso)
      options['checkworkdir']="true"
      options['getiso']="true"
      ;;
    installrequired|checkrequired)
      options['installrequiredpackages']="true"
      ;;
    checkworkdir|checkdirs)
      options['checkworkdir']="true"
      ;;
    justiso)
      options['justiso']="true"
      ;;
    createautoinstall)
      options['createautoinstall']="true"
      ;;
    runchrootscript|execchrootscript|executechrootscript)
      options['runchrootscript']="true"
      ;;
    createiso|fulliso)
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['runchrootscript']="true"
      options['fulliso']="true"
      ;;
    createisoandsquashfs)
      options['updatesquashfs']="true"
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['runchrootscript']="true"
      options['fulliso']="true"
     ;;
    createdockeriso)
      options['docker']="true"
      options['checkdocker']="true"
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['runchrootscript']="true"
      options['fulliso']="true"
      ;;
    createdockerisoandsquashfs)
      options['updatesquashfs']="true"
      options['docker']="true"
      options['checkdocker']="true"
      options['checkworkdir']="true"
      options['installrequiredpackages']="true"
      options['runchrootscript']="true"
      options['fulliso']="true"
      ;;
    createisovm)
      vm['type']="kvm"
      options['installrequiredpackages']="true"
      options['createisovm']="true"
      ;;
    iso['delete']}isovm)
      vm['type']="kvm"
      options['installrequiredpackages']="true"
      options['deleteisovm']="true"
      ;;
    createcivm)
      vm['type']="kvm"
      options['installrequiredpackages']="true"
      options['createcivm']="true"
      ;;
    iso['delete']}civm)
      vm['type']="kvm"
      options['installrequiredpackages']="true"
      options['deletecivm']="true"
      ;;
    queryiso)
      options['query']="true"
      ;;
    unmount)
      options['unmount']="true"
      ;;
    oldinstaller)
      options['oldinstaller']="true"
      ;;
    listalliso|listallisos|listiso|listisos)
      options['listisos']="true"
      ;;
    test)
      options['testmode']="true"
      ;;
    *)
      warning_message "Action \"${iso['action']}\" is not a valid action"
      exit
      ;;
  esac
  case ${iso['delete']} in
    files)
      options['force']="true"
      ;;
    all)
      options['forceall']="true"
      ;;
    *)
      options['force']="false"
      options['forceall']="false"
  esac
}
