# Function: print_help
#
# Print script help information

print_help () {
  cat <<-HELP

  Usage: ${0##*/} [OPTIONS...]
    --oldrelease           Old release (used for copying file from an older release ISO - default: $DEFAULT_OLD_ISO_RELEASE)
    --country              Country (used for sources.list mirror - default: $DEFAULT_ISO_COUNTRY)
    --isourl               Specify ISO URL (default: $DEFAULT_ISO_URL)
    --prefix               Prefix to add to ISO name
    --suffix               Suffix to add to ISO name
    --block                Block kernel module(s) (default: $DEFAULT_ISO_BLOCKLIST)
    --allow                Load additional kernel modules(s)
    --oldisourl            Old release ISO URL (used with --oldrelease) (default: $DEFAULT_OLD_ISO_URL)
    --oldinputfile         Old release ISO (used with --oldrelease) (default: $DEFAULT_OLD_ISO_RELEASE)
    --search               Search output for value (eg --action listallisos --search efi)
    --codename|--disto     Linux release codename or distribution (default: $DEFAULT_ISO_CODENAME)
    --action:              Action to perform (e.g. createiso, justiso, runchrootscript, checkdocker, installrequired)
    --layout|--vmsize:     Layout or VM disk size (default: $DEFAULT_ISO_LAYOUT/$DEFAULT_VM_SIZE)
    --bootserverip:        NFS/Bootserver IP (default: $DEFAULT_BOOT_SERVER_IP)
    --cidr:                CIDR (default: $DEFAULT_ISO_CIDR)
    --sshkeyfile:          SSH key file to use as SSH key (default: $MASKED_DEFAULT_ISO_SSH_KEY_FILE)
    --dns:                 DNS Server (ddefault: $DEFAULT_ISO_DNS)
    --bootdisk:            Boot Disk devices (default: $DEFAULT_ISO_DEVICES)
    --locale:              LANGUAGE (default: $DEFAULT_ISO_LOCALE)
    --lcall:               LC_ALL (default: $DEFAULT_ISO_LC_ALL)
    --bmcusername:         BMC/iDRAC User (default: $DEFAULT_BMC_USERNAME)
    --delete:              Remove previously created files (default: $FORCE_MODE)
    --gateway:             Gateway (default $DEFAULT_ISO_GATEWAY)
    --grubmenu|--vmname:   Set default grub menu or VM name (default: $DEFAULT_ISO_GRUB_MENU/$SCRIPT_NAME)
    --hostname             Hostname (default: $DEFAULT_ISO_HOSTNAME)
    --help                 Help/Usage Information
    --ip:                  IP Address (default: $DEFAULT_ISO_IP)
    --inputiso|--vmiso:    Input/base ISO file (default: $DEFAULT_INPUT_FILE_BASE)
    --grubfile             GRUB file (default: $DEFAULT_ISO_GRUB_FILE_BASE)
    --autoinstalldir       Directory where autoinstall config files are stored on ISO (default: $DEFAULT_ISO_AUTOINSTALL_DIR)
    --kernel|--vmtype:     Kernel package or VM type (default: $DEFAULT_ISO_KERNEL/$DEFAULT_VM_TYPE)
    --kernelargs|--vmcpus: Kernel arguments (default: $DEFAULT_ISO_KERNEL_ARGS)
    --release:             LSB release (default: $DEFAULT_ISO_RELEASE)
    --bmcip:               BMC/iDRAC IP (default: $DEFAULT_BMC_IP)
    --installtarget:       Where the install mounts the target filesystem (default: $DEFAULT_ISO_TARGET_MOUNT)
    --installmount:        Where the install mounts the CD during install (default: $DEFAULT_ISO_INSTALL_MOUNT)
    --bootserverfile       Boot sever file (default: $DEFAULT_BOOT_SERVER_FILE_BASE)
    --nic|--vmnic:         Network device (default: $DEFAULT_ISO_NIC/$DEFAULT_VM_NIC)
    --isopackages:         List of packages to install (default: $DEFAULT_ISO_INSTALL_PACKAGES)
    --outputiso:           Output ISO file (default: $DEFAULT_OUTPUT_FILE_BASE)
    --password:            Password (default: $DEFAULT_ISO_PASSWORD)
    --chrootpackages:      List of packages to add to ISO (default: $DEFAULT_PACKAGES)
    --build:               Type of ISO to build (default: $DEFAULT_ISO_BUILD_TYPE)
    --arch:                Architecture (default: $DEFAULT_ISO_ARCH)
    --realname:            Realname (default $DEFAULT_ISO_REALNAME)
    --serialportspeed:     Serial Port Speed (default: $DEFAULT_ISO_SERIAL_PORT_SPEED0,$DEFAULT_ISO_SERIAL_PORT_SPEED1)
    --swapsize|--vmram:    Swap or VM memory size (default $DEFAULT_ISO_SWAPSIZE/$DEFAULT_VM_RAM)
    --squashfsfile:        Squashfs file (default: $DEFAULT_ISO_SQUASHFS_FILE_BASE)
    --timezone:            Timezone (default: $DEFAULT_ISO_TIMEZONE)
    --serialportaddress:   Serial Port Address (default: $DEFAULT_ISO_SERIAL_PORT_ADDRESS0,$DEFAULT_ISO_SERIAL_PORT_ADDRESS1)
    --username:            Username (default: $DEFAULT_ISO_USERNAME)
    --postinstall:         Postinstall action (e.g. installpackages, upgrade, distupgrade, installdrivers, all, autoupgrades)
    --version              Display Script Version
    --serialport:          Serial Port (default: $DEFAULT_ISO_SERIAL_PORT0,$DEFAULT_ISO_SERIAL_PORT1)
    --workdir:             Work directory (default: $MASKED_DEFAULT_WORK_DIR)
    --preworkdir:          Docker work directory (used internally)
    --isovolid:            ISO Volume ID (default: $DEFAULT_ISO_VOLID)
    --grubtimeout:         Grub timeout (default: $DEFAULT_ISO_GRUB_TIMEOUT)
    --allowpassword        Allow password access via SSH (default: $DEFAULT_ISO_ALLOW_PASSWORD)
    --bmcpassword:         BMC/iDRAC password (default: $DEFAULT_BMC_PASSWORD)
    --options:             Options (e.g. nounmount, testmode, bios, uefi, verbose, interactive)
    --volumemanager:       Volume Managers (default: $DEFAULT_ISO_VOLMGRS)
    --zfsfilesystems:      ZFS filesystems (default: $DEFAULT_ZFS_FILESYSTEMS)
    --userdata:            Use a custom user-data file (default: generate automatically)
    --oeminstall:          OEM Install Type (default $DEFAULT_ISO_OEM_INSTALL)
    --sourceid:            Source ID ($DEFAULT_ISO_SOURCE_ID) 
    --installmode:         Install Mode ($DEFAULT_ISO_INSTALL_MODE)
    --passwordalgorithm:   Password Algorithm ($DEFAULT_ISO_PASSWORD_ALGORITHM)
    --bootloader:          Boot Loader Location ($DEFAULT_ISO_BOOT_LOADER_LOCATION)
    --selinux:             SELinux Mode ($DEFAULT_ISO_SELINUX)
    --firewall:            Firewall ($DEFAULT_ISO_FIREWALL)
    --allow:               Allow Services ($DEFAULT_ISO_ALLOW_SERVICE)
    --onboot:              Enable Network on Boot ($DEFAULT_ISO_ONBOOT)
    --enableservice        Enable Service ($DEFAULT_ISO_ENABLE_SERVICE)
    --disableservice       Disable Service ($DEFAULT_ISO_DISABLE_SERVICE)
    --gecos                GECOS Field Entry ($DEFAULT_ISO_DISABLE_SERVICE)
    --installsource        Install Source ($DEFAULT_ISO_INSTALL_SOURCE)
HELP
  exit
}
