#!/usr/bin/env bash

# shellcheck disable=SC2034
# shellcheck disable=SC2129
# shellcheck disable=SC2153
# shellcheck disable=SC2154

# Function: create_kickstart_iso
#
# Create kickstart ISO (e.g. Rocky Linux)

create_kickstart_iso () {
  if [ ! -f "/usr/bin/xorriso" ]; then
    install_required_packages "${options['requiredpackages']}"
  fi
  if [ "${options['testmode']}" = "false" ]; then
    handle_output "# Creating ISO" "TEXT"
    check_file_perms "${iso['outputfile']}"
    cd "${iso['newdir']}/cd" || exit
    sudo mkisofs -o "${iso['outputfile']}" -b isolinux/isolinux.bin -c isolinux/boot.cat \
    -boot-load-size 4 -boot-info-table -no-emul-boot -eltorito-alt-boot \
    -eltorito-boot images/efiboot.img -no-emul-boot -R -J -V "${iso['label']}" -T .
    check_file_perms "${iso['outputfile']}"
  fi
}

# Function: create_kickstart_file
#
# Create kickstart files (e.g. Rocky Linux)

prepare_kickstart_files () {
  iso['ksdir']="${iso['newdir']}/cd/"
  INCLUDE_DISK_FILE="/tmp/first-disk.cfg"
  INCLUDE_NIC_FILE="/tmp/first-nic.cfg"
  if [ "${options['isolinuxfile']}" = "true" ] && [ "${options['autoinstall']}" = "true" ]; then
    print_file "${iso['autoinstallfile']}"
    ksvalidator "${iso['autoinstallfile']}"
    sudo cp "${iso['autoinstallfile']}" "${iso['ksdir']}"
  else
    for iso_volmgr in ${iso['volumemanager']}; do
      iso['ksfile']="${iso['workdir']}/files/${iso_volmgr}.cfg"
      date=$( date )
      echo "# Kistart file generated by ${script['name']} on ${datei}" > "${iso['ksfile']}"
      if [ "${options['mediacheck']}" = "true" ]; then
        echo "mediacheck" >> "${iso['ksfile']}"
      fi
  #    echo "${iso['installmode']}" >> "${iso['ksfile']}"
      echo "${iso['installsource']}" >> "${iso['ksfile']}"
      echo "%pre" >> "${iso['ksfile']}"
      if [ "${iso['disk']}" = "first-disk" ]; then
        if [ ! "${iso_volmgr}" = "lvm" ]; then
          echo "FIRST_DISK=\$( /bin/lsblk -x TYPE |grep disk |grep -v SWAP |sort |head -1 |awk '{print \$1}' )" > "${iso['ksfile']}"
          echo "echo \"# First Disk\" > $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
          echo "echo \"bootloader --timeout=${iso['grubtimeout']} --location=${iso['bootloader']} --append=\\\"${iso['kernel']}ARGS\\\" --boot-drive=/dev/\\$FIRST_DISK\" >> $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
          echo "echo \"clearpart --all --drives=/dev/\\$FIRST_DISK\" >> $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
          echo "echo \"part /boot --size=${iso['bootsize']} --fstype=\\\"${iso_volmgr}\\\" --ondisk=/dev/\\$FIRST_DISK\" >> $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
          echo "echo \"part ${iso['lvname']} --size=-1 --grow --fstype=\\\"lvmpv\\\" --ondisk=/dev/\\$FIRST_DISK\" >> $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
          echo "echo \"part /boot/efi --size=${iso['bootsize']} --asprimary --fstype=\\\"efi\\\" --ondisk=/dev/\\$FIRST_DISK\" >> $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
        fi
      fi
      if [ "${iso['nic']}" = "first-nic" ]; then
        echo "echo\"# First NIC\" > $INCLUDE_NIC_FILE" >> "${iso['ksfile']}"
        echo "FIRST_NIC=\$(lshw -class network -short |awk '{print \$2}' |grep ^e |head -1)\" >> $INCLUDE_NIC_FILE" >> "${iso['ksfile']}"
      fi
      echo "%end" >> "${iso['ksfile']}"
      echo "lang ${iso['locale']}" >> "${iso['ksfile']}"
      echo "keyboard ${iso['country']}" >> "${iso['ksfile']}"
      echo "timezone --utc ${iso['timezone']}" >> "${iso['ksfile']}"
      echo "firstboot --${options['firstboot']}" >> "${iso['ksfile']}"
      if [ "${iso_volmgr}" = "lvm" ]; then
        echo "autopart --type=lvm" >> "${iso['ksfile']}"
      else
        if [ "${iso['disk']}" = "first-disk" ]; then
          echo "%include $INCLUDE_DISK_FILE" >> "${iso['ksfile']}"
        else
          echo "bootloader --timeout=${iso['grubtimeout']} --location=${iso['bootloader']} --append=\"${iso['kernel']}ARGS\" --boot-drive=${iso['disk']}" >> "${iso['ksfile']}"
          echo "clearpart --all --drives=${iso['disk']}" >> "${iso['ksfile']}"
          echo "part /boot --size=${iso['bootsize']} --fstype=\"${iso_volmgr}\" --ondisk=${iso['disk']}" >> "${iso['ksfile']}"
          echo "part ${iso['lvname']} --size=-1 --grow --fstype=\"${iso_volmgr}\" --ondisk=${iso['disk']}" >> "${iso['ksfile']}"
          echo "part /boot/efi --size=${iso['bootsize']} --asprimary --fstype=\"efi\" --ondisk=${iso['disk']}" >> "${iso['ksfile']}"
        fi
        echo "volgroup ${iso['vgname']} --pesize=${iso['pesize']} ${iso['lvname']}" >> "${iso['ksfile']}"
        echo "logvol / --fstype ${iso_volmgr} --vgname ${iso['vgname']} --size=${iso['rootsize']} --name=root" >> "${iso['ksfile']}"
        echo "logvol swap --vgname ${iso['vgname']} --size=${iso['swapsize']} --name=swap" >> "${iso['ksfile']}"
      fi
  #    echo "auth --enableshadow --passalgo=${iso['passwordalgorithm']}" >> "${iso['ksfile']}"
      echo "selinux --${iso['selinux']}" >> "${iso['ksfile']}"
      if [ "${iso['firewall']}" = "enabled" ]; then
        echo "firewall --${iso['firewall']} --service=${iso['allowservice']}" >> "${iso['ksfile']}"
      else
        echo "firewall --${iso['firewall']}" >> "${iso['ksfile']}"
      fi
      if [ "${iso['nic']}" = "first-nic" ]; then
        NETWORK="network --hostname=${iso['hostname']} --bootproto=${iso['bootproto']} --device=\$FIRST_NIC --onboot=${iso['onboot']}"
      else
        NETWORK="network --hostname=${iso['hostname']} --bootproto=${iso['bootproto']} --device=${iso['nic']} --onboot=${iso['onboot']}"
      fi
      if [ "${options['ipv4']}" = "false" ]; then
        NETWORK="$NETWORK --noipv4"
      fi
      if [ "${options['ipv6']}" = "false" ]; then
        NETWORK="$NETWORK --noipv6"
      fi
      if [ "${options['activate']}" = "true" ]; then
        NETWORK="$NETWORK --activate"
      else
        NETWORK="$NETWORK --no-activate"
      fi
      if [ "${options['defaultroute']}" = "false" ]; then
        NETWORK="$NETWORK --nodefroute"
      fi
      if [ "${options['dhcp']}" = "false" ]; then
        NETWORK="$NETWORK --ip=${iso['ip']} --netmask=${iso['netmask']} --gateway=${iso['gateway']} --nameserver=${iso['dns']}"
      fi
      if [ "${iso['nic']}" = "first-nic" ]; then
        echo "%include $INCLUDE_NIC_FILE" >> "${iso['ksfile']}"
        echo "echo \"$NETWORK\" >> $INCLUDE_NIC_FILE" >> "${iso['ksfile']}"
      else
        echo "$NETWORK" >> "${iso['ksfile']}"
      fi
      echo "services --enabled=${iso['enableservice']} --disabled=${iso['disableservice']}" >> "${iso['ksfile']}"
      if [ "${options['plaintextpassword']}" = "true" ]; then
        ROOT_PW="rootpw --plaintext ${iso['password']}"
        USER_PW="user --name=${iso['username']} --group=${iso['groups']} --password=${iso['password']} --plaintext --gecos=\"${iso['gecos']}\"" >> "${iso['ksfile']}"
        SSH_PW="sshpw --username=${iso['installusername']} ${iso['installpassword']}"
      else
        ROOT_PW="rootpw --iscrypted ${iso['passwordcrypt']}" >> "${iso['ksfile']}"
        USER_PW="user --name=${iso['username']} --group=${iso['groups']} --password=${iso['passwordcrypt']} --iscrypted --gecos=\"${iso['gecos']}\"" >> "${iso['ksfile']}"
        SSH_PW="sshpw --username=${iso['installusername']} --iscrypted --password=${iso['installpasswordcrypt']}"
      fi
      if [ "${options['lockroot']}" = "true" ]; then
        ROOT_PW="$ROOT_PW --lock"
      fi
      echo "$ROOT_PW" >> "${iso['ksfile']}"
      echo "$USER_PW" >> "${iso['ksfile']}"
      if [ "${options['installuser']}" = "true" ]; then
        echo "$SSH_PW" >> "${iso['ksfile']}"
      fi
      echo "%packages" >> "${iso['ksfile']}"
      for PACKAGE in ${iso['packages']}; do
        echo "$PACKAGE" >> "${iso['ksfile']}"
      done
      echo "%end" >> "${iso['ksfile']}"
      print_file "${iso['ksfile']}"
      if [ -n "$( command -v ksvalidator )" ]; then
        ksvalidator "${iso['ksfile']}"
      fi
      if [ "${options['testmode']}" = "false" ]; then
        sudo cp "${iso['ksfile']}" "${iso['ksdir']}"
      fi
    done
    if [ "${options['autoinstall']}" = "true" ]; then
      if [ -n "$( command -v ksvalidator )" ]; then
        ksvalidator "${iso['autoinstallfile']}"
      fi
      print_file "${iso['autoinstallfile']}"
      if [ "${options['testmode']}" = "false" ]; then
        sudo cp "${iso['autoinstallfile']}" "${iso['ksdir']}/custom.cfg"
      fi
    fi
  fi
}

# Function: prepare_kickstart_iso['grubmenu']}
#
# Prepare kickstart grub, isolinux, etc files

prepare_kickstart_grubmenu () {
  TMP_LINUX_CFG="${iso['workdir']}/files/isolinux.cfg"
  TMP_GRUB_CFG="${iso['workdir']}/files/grub.cfg"
  ISO_LINUX_CFG="${iso['newdir']}/cd/isolinux/isolinux.cfg"
  ISO_GRUB_CFG="${iso['newdir']}/cd/EFI/BOOT/grub.cfg"
  iso['label']="${iso['realname']}-${iso['majorrelease']}-${iso['minorrelease']}-${iso['arch']}-$ISO_TYPE"
  ISO_REPO_DIR="/run/install/repo"
  echo "default ${iso['grubmenu']}" > "$TMP_LINUX_CFG"
  counter=0
  iso['kernelserialargs']="console=${iso['serialporta']},${iso['serialportspeeda']} console=${iso['serailportb']},${iso['serialportspeedb']}"
  if [ "${options['ksquiet']}" = "true" ]; then
    iso['kernelargs']="${iso['kernelargs']} quiet"
  fi
  if [ "${options['kstext']}" = "true" ]; then
    iso['kernelargs']="${iso['kernelargs']} inst.text"
  fi
  if [ "${options['isolinuxfile']}" = "true" ]; then
    print_file "${iso['isolinuxfile']}"
    print_file "${iso['grubfile']}"
    if [ "${options['testmode']}" = "false" ]; then
      sudo cp "${iso['isolinuxfile']}" "$ISO_LINUX_CFG"
      sudo cp "${iso['grubfile']}" "$ISO_GRUB_CFG"
    fi
  else
    for iso_volmgr in ${iso['volumemanager']}; do
      if ! [ "${iso_volmgr}" = "custom" ]; then
        echo "label ${counter}" >> "$TMP_LINUX_CFG"
        echo "  menu label ^${iso['volid']}:${iso_volmgr}:${iso['disk']}:${iso['nic']} (${iso['kernel']}ARGS)" >> "$TMP_LINUX_CFG"
        echo "  kernel vmlinuz" >> "$TMP_LINUX_CFG"
        echo "  append initrd=initrd.img inst.stage2=hd:LABEL=${iso['label']} ${iso['kernel']}ARGS inst.ks=hd:LABEL=${iso['label']}:/${iso_volmgr}.cfg" >> "$TMP_LINUX_CFG"
        counter=$(( counter+1 ))
      fi
    done
    if [ "${options['autoinstall']}" = "true" ]; then
      echo "label custom" >> "$TMP_LINUX_CFG"
      echo "  menu label ^${iso['volid']}:custom (${iso['kernel']}ARGS)" >> "$TMP_LINUX_CFG"
      echo "  kernel vmlinuz" >> "$TMP_LINUX_CFG"
      echo "  append initrd=initrd.img inst.stage2=hd:LABEL=${iso['label']} ${iso['kernel']}ARGS inst.ks=hd:LABEL=${iso['label']}:/custom.cfg" >> "$TMP_LINUX_CFG"
    fi
    echo "label install" >> "$TMP_LINUX_CFG"
    echo "  menu label ^Install a Rocky Linux system" >> "$TMP_LINUX_CFG"
    echo "  kernel vmlinuz" >> "$TMP_LINUX_CFG"
    echo "  append initrd=initrd.img inst.stage2=hd:LABEL=${iso['label']} ${iso['kernel']}ARGS" >> "$TMP_LINUX_CFG"
    echo "label rescue" >> "$TMP_LINUX_CFG"
    echo "  menu label ^Rescue a Rocky Linux system" >> "$TMP_LINUX_CFG"
    echo "  kernel vmlinuz" >> "$TMP_LINUX_CFG"
    echo "  append initrd=initrd.img inst.stage2=hd:LABEL=${iso['label']} ${iso['kernel']}ARGS" >> "$TMP_LINUX_CFG"
    echo "label memtest" >> "$TMP_LINUX_CFG"
    echo "  menu label Test ^Memory" >> "$TMP_LINUX_CFG"
    echo "  kernel memtest" >> "$TMP_LINUX_CFG"
    echo "label hd" >> "$TMP_LINUX_CFG"
    echo "  menu label ^Boot from first hard drive" >> "$TMP_LINUX_CFG"
    echo "  localboot 0x80" >> "$TMP_LINUX_CFG"
    print_file "$TMP_LINUX_CFG"
    if [ "${options['testmode']}" = "false" ]; then
      sudo cp "$TMP_LINUX_CFG" "$ISO_LINUX_CFG"
    fi
    echo "set timeout=${iso['grubtimeout']}" > "$TMP_GRUB_CFG"
    echo "set default=${iso['grubmenu']}" >> "$TMP_GRUB_CFG"
    echo "" >> "$TMP_GRUB_CFG"
    echo "function load_video {" >> "$TMP_GRUB_CFG"
    echo "  insmod efi_gop" >> "$TMP_GRUB_CFG"
    echo "  insmod efi_uga" >> "$TMP_GRUB_CFG"
    echo "  insmod video_bochs" >> "$TMP_GRUB_CFG"
    echo "  insmod video_cirrus" >> "$TMP_GRUB_CFG"
    echo "}" >> "$TMP_GRUB_CFG"
    echo "" >> "$TMP_GRUB_CFG"
    echo "load_video" >> "$TMP_GRUB_CFG"
    echo "set gfxpayload=keep" >> "$TMP_GRUB_CFG"
    echo "insmod gzio" >> "$TMP_GRUB_CFG"
    echo "insmod part_gpt" >> "$TMP_GRUB_CFG"
    echo "insmod ext2" >> "$TMP_GRUB_CFG"
    echo "" >> "$TMP_GRUB_CFG"
    echo "search --no-floppy --set=root -l '${iso['label']}'" >> "$TMP_GRUB_CFG"
    echo "" >> "$TMP_GRUB_CFG"
    if [ "${options['autoinstall']}" = "true" ]; then
      echo "menuentry '${iso['volid']}:custom (${iso['kernelserialargs']})' {" >> "$TMP_GRUB_CFG"
      echo "  linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=${iso['label']} ${iso['kernel']}ARGS inst.ks=hd:LABEL=${iso['label']}:/custom.cfg" >> "$TMP_GRUB_CFG"
      echo "  initrdefi /images/pxeboot/initrd.img" >> "$TMP_GRUB_CFG"
      echo "}" >> "$TMP_GRUB_CFG"
    fi
    for iso_volmgr in ${iso['volumemanager']}; do
      if ! [ "${iso_volmgr}" = "custom" ]; then
        echo "menuentry '${iso['volid']}:${iso_volmgr}:${iso['disk']}:${iso['nic']} (${iso['kernelserialargs']})' {" >> "$TMP_GRUB_CFG"
        echo "  linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=${iso['label']} ${iso['kernel']}ARGS inst.ks=hd:LABEL=${iso['label']}:/${iso_volmgr}.cfg" >> "$TMP_GRUB_CFG"
        echo "  initrdefi /images/pxeboot/initrd.img" >> "$TMP_GRUB_CFG"
        echo "}" >> "$TMP_GRUB_CFG"
      fi
    done
    echo "menuentry 'Install ${iso['volid']} (${iso['kernelserialargs']})' {" >> "$TMP_GRUB_CFG"
    echo "  linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=${iso['label']} ${iso['kernelserialargs']}" >> "$TMP_GRUB_CFG"
    echo "  initrdefi /images/pxeboot/initrd.img" >> "$TMP_GRUB_CFG"
    echo "}" >> "$TMP_GRUB_CFG"
    echo "menuentry 'Rescue ${iso['volid']} (${iso['kernelserialargs']})' {" >> "$TMP_GRUB_CFG"
    echo "  linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=${iso['label']} ${iso['kernelserialargs']}" >> "$TMP_GRUB_CFG"
    echo "  initrdefi /images/pxeboot/initrd.img" >> "$TMP_GRUB_CFG"
    echo "}" >> "$TMP_GRUB_CFG"
    echo "menuentry 'Boot from next volume' {" >> "$TMP_GRUB_CFG"
    echo "  exit 1" >> "$TMP_GRUB_CFG"
    echo "}" >> "$TMP_GRUB_CFG"
    if [[ "${iso['boottype']}" =~ "efi" ]]; then
      echo "menuentry 'UEFI Firmware Settings' {" >> "$TMP_GRUB_CFG"
      echo "  fwsetup" >> "$TMP_GRUB_CFG"
      echo "}" >> "$TMP_GRUB_CFG"
    fi
    print_file "$TMP_GRUB_CFG"
    if [ "${options['testmode']}" = "false" ]; then
      sudo cp "$TMP_GRUB_CFG" "$ISO_GRUB_CFG"
    fi
  fi
}

# Function: prepare_kickstart_iso
#
# Prepare kickstart ISO (e.g. Rocky Linux)

prepare_kickstart_iso () {
  prepare_kickstart_files
  prepare_kickstart_grubmenu
}
