# Generated by Anaconda 34.25.3.8
# Generated by pykickstart v3.32
#version=RHEL9
# Use graphical install
graphical
repo --name="AppStream" --baseurl=file:///run/install/sources/mount-0000-cdrom/AppStream

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

# Keyboard layouts
keyboard --xlayouts='au'
# System language
lang en_AU.UTF-8

# Use CDROM installation media
cdrom

%packages
@^graphical-server-environment

%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.6.0
ignoredisk --only-use=vda
# System bootloader configuration
bootloader --append="crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M" --location=mbr --boot-drive=vda
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone Australia/Melbourne --utc

#Root password
rootpw --lock
user --groups=wheel --name=rocky --password=$6$MK6vTJiQcHG4rqF3$z6ofnFB9ICCkhHmDadUAtX3zy9L5GPWccIOVxF/tLiAUqCH0uctvkHb2xs4SnX76Da5GgKC8dc0cALEiPE59r1 --iscrypted --gecos="rocky"

